- name: Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.saitejasroboshop.store -uroot -pRoboShop@1 < /app/db/schema.sql

- name: Load User creation
  ansible.builtin.shell: mysql -h mysql-dev.saitejasroboshop.store -uroot -pRoboShop@1 < /app/db/app-user.sql

- name: Load Master Data
  ansible.builtin.shell: mysql -h mysql-dev.saitejasroboshop.store -uroot -pRoboShop@1 < /app/db/master-data.sql