- name: Install Go
  ansible.builtin.dnf:
    name:
      - golang
    state: installed

- name: Include artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yml


- name: Initialize Go Component
  ansible.builtin.shell: go mod init {{ component_name }}
  args:
    chdir: /app

- name: Install GoLang Dependencies
  ansible.builtin.shell: go get; go build
  args:
    chdir: /app

- name: Include systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml