- name: Install Python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: installed


- name: Include artifact_download
  ansible.builtin.include_tasks:
    file: artifact_download.yml


- name: Install Python Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Include systemd_setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml