- name: Copy SystemD service file
  ansible.builtin.copy:
    src: "{{ component_name }}.service"
    dest: /etc/systemd/system/{{ component_name }}.service

- name: Start Service
  ansible.builtin.systemd_service:
    name: "{{ component_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes