- name: Get secrets for this app
  ansible.builtin.set_fact:
    component_secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'roboshop-{{ env }}/data/{{ component_name }} token={{ vault_token }} url=http://vault-internal.saitejasroboshop.store:8200') }}"


- name: Copy SystemD service file
  ansible.builtin.template:
    src: component.service
    dest: /etc/systemd/system/{{ component_name }}.service

- name: Start Service
  ansible.builtin.systemd_service:
    name: "{{ component_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes